### ISSUE TITLE
app_links in carplay supported app

### ISSUE THREAD

**Issue by glettl** [llfbandit/app_links#81] opened 2023-11-14 16:05 UTC
Hello,

I'm currently facing the following issue with app_links in combination with flutter_carplay.

According to the flutter_carplay documentation I need to change the AppDelegate.swift to

```

import UIKit
import Flutter

@UIApplicationMain
@objc class AppDelegate: FlutterAppDelegate {
  override func application(
    _ application: UIApplication,
    didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?
 ) -> Bool {
  //     GeneratedPluginRegistrant.register(with: self)
  //     return super.application(application, didFinishLaunchingWithOptions: launchOptions)
      return true;
  }
}
```

and create a SceneDelegate.swift with the following content:

```
@available(iOS 13.0, *)
class SceneDelegate: UIResponder, UIWindowSceneDelegate {
    var window: UIWindow?

    func scene(_ scene: UIScene, willConnectTo session: UISceneSession, options connectionOptions: UIScene.ConnectionOptions) {
        guard let windowScene = scene as? UIWindowScene else { return }

        window = UIWindow(windowScene: windowScene)

        let flutterEngine = FlutterEngine(name: "SceneDelegateEngine")
        flutterEngine.run()
        GeneratedPluginRegistrant.register(with: flutterEngine)
        let controller = FlutterViewController.init(engine: flutterEngine, nibName: nil, bundle: nil)
        window?.rootViewController = controller
        window?.makeKeyAndVisible()
    }
}

```

and add the new Scene and the Carplay Scene in the Info.plist

```
<dict>
		<key>UISceneConfigurations</key>
		<dict>
			<key>CPTemplateApplicationSceneSessionRoleApplication</key>
			<array>
				<dict>
					<key>UISceneClassName</key>
					<string>CPTemplateApplicationScene</string>
					<key>UISceneConfigurationName</key>
					<string>MyApp-Car</string>
					<key>UISceneDelegateClassName</key>
					<string>flutter_carplay.FlutterCarPlaySceneDelegate</string>
				</dict>
			</array>
			<key>UIWindowSceneSessionRoleApplication</key>
			<array>
				<dict>
					<key>UISceneClassName</key>
					<string>UIWindowScene</string>
					<key>UISceneConfigurationName</key>
					<string>Phone</string>
					<key>UISceneDelegateClassName</key>
					<string>$(PRODUCT_MODULE_NAME).SceneDelegate</string>
				</dict>
			</array>
		</dict>
	</dict>
```

Unfortunately, now the app is opened using a custom url scheme, but getInitialAppLink is `null` and uriLinkStream is not fired. I assume it's because `return super.application(application, didFinishLaunchingWithOptions: launchOptions)` isn't called any longer.

I tried removing the carplay related code and everything works fine.

Could you please help me to fix this problem?

**Comment by glettl** [comment] 2023-11-14 17:02
I tried the this solution, but unfortunately I get this error on startup
![image](https://github.com/llfbandit/app_links/assets/8844059/7f57793a-0acb-49b8-bd62-440ae6a259a8)

**Comment by llfbandit** [comment] 2023-11-30 11:23
This should be somehow available in app_links 3.5.0-beta.1. Please have a look to the README file.
Feedback appreciated!

**Comment by bverhagen** [comment] 2023-12-07 22:43
The same issue impacts the macOS platform. Retesting with version 3.5.0-beta.1 as suggested by the linked comment for issue #70 fixes the problem.

**Comment by glettl** [comment] 2023-12-09 07:59
Unfortunately, the version 3.5.0-beta.1 does not build.

Failed to build iOS app
Error (Xcode): .dart_tool/flutter_build/dart_plugin_registrant.dart:112:9:
Error: Undefined name 'AppLinksPluginLinux'.

Also did a flutter pub clean, and pod update.

Thats why I used 3.5.0-beta.2, which builds but it does not work if the app is closed and opened via a deeplink. The app opens but the deeplink is not recognized.

**Comment by llfbandit** [comment] 2023-12-14 13:50
Released in v3.5.0.
Update your specifics to catch links.

**Closed by llfbandit** 2023-12-14 13:50 UTC

**Comment by renatomotorline** [comment] 2024-07-04 11:06
> I tried the this solution, but unfortunately I get this error on startup ![image](https://private-user-images.githubusercontent.com/8844059/282861356-7f57793a-0acb-49b8-bd62-440ae6a259a8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAwOTA2MzAsIm5iZiI6MTcyMDA5MDMzMCwicGF0aCI6Ii84ODQ0MDU5LzI4Mjg2MTM1Ni03ZjU3NzkzYS0wYWNiLTQ5YjgtYmQ2Mi00NDBhZTZhMjU5YTgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcwNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MDRUMTA1MjEwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDVjNWExNDk5YzAwZTc4MDY4NjE5NmFkOTMyMWVmMzk1MmM1MTkwZDQyNTVmZDk1ZTFjYjM5YjFhMzNkMmNmZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.f5EirfuaWqWADWbd739BZcdouhXLlUb8nvkzHEWxDdo)

@glettl Have you been able to fix this problem?
I'm using the latest version(^6.1.4) but already tried with the 3.5.0. Also changed the App Delegate and Scene Delegate.

**Comment by EtcGonza** [comment] 2024-07-10 16:35
I'm using the 6.1.4 version too and I have the same issue. Someone has fix it?

<img width="731" alt="Captura de pantalla 2024-07-10 a la(s) 1 33 50 p  m" src="https://github.com/llfbandit/app_links/assets/44512291/3125afce-8906-4913-9e5d-099d62cf7540">

**Comment by tsunhousam91** [comment] 2024-08-27 03:18
I also have this issue, my app also support carplay, so I changed the AppDelegate and SceneDelegate, and I can not receive first link when open app from closed state.  ( If app is in background, then I can receive link)

**Comment by tsunhousam91** [comment] 2024-08-27 03:19
I think this issue might be re opened again, the issue is not solved yet.
